### ISSUE TITLE
Is that possible to convert md files into json ?

### ISSUE THREAD

**Issue by NejiSoltani** [RasaHQ/starter-pack#3]
I want to use Json in order to save the files into a NoSql database.

Is that possible ?

**Comment by tmbo** [comment]
Yes, there is a script as part of rasa nlu that does that. Try running 
`python -m rasa_nlu.convert --data_file XYZ --out_file ABC --format json` passing in source data for `XYZ` and target data for `ABC`.

**Comment by Basit-qc** [comment]
What @tmbo suggested, is correct but it needs an output file path.
To convert .md file to json without creating a new file, I used following snippets of code to convert .md file to JSON format
```
from rasa_nlu import training_data
td = training_data.load_data('path/to/file')
output = td.as_json(indent=2)
json_data = json.loads(output)
```

**Comment by karthikbalu** [comment]
Is it possible to convert both nlu_data.md and stories.md to json format?

**Comment by Basit-qc** [comment]
@karthikbalu As far as I know, only nlu_data.md can be converted into JSON. Above converter fails for story files.
I could not found any method that converts stories.md file to JSON. Would be great if someone can share such method :)

**Comment by njain51** [comment]
thanks for it, for new version of rasa 1.0.7. following command will work: 
rasa data convert nlu --data ./data/nlu.md --out ./data/data.json --format json

**Comment by thethinkingmonks** [comment]
Thank for below command it works for me
rasa data convert nlu --data ./data/nlu.md --out ./data/data.json --format json
